version: "3.7"

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - BOT_MIRROR_TOKEN=${BOT_MIRROR_TOKEN}
      - BOT_DA_VINCI_TOKEN=${BOT_DA_VINCI_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
